client_config_backend: settings
client_config:
  client_id: 356767572511-5me78ajji10nku2g9ram3fne3j9j8ogl.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.metadata